/**
 * The platform table and the generator for `build/entry.ts`, the entrypoint
 * `bun build --compile` is pointed at.
 *
 * Kept apart from `build-binary.ts` so the interesting half — string in, string
 * out — is testable without compiling a 60 MB executable.
 */

/** The Bun target is `bun-` plus one of these, verbatim. */
export const PLATFORMS = [
	"darwin-arm64",
	"darwin-x64",
	"linux-x64",
	"linux-arm64",
] as const;

export type Platform = (typeof PLATFORMS)[number];

export function isPlatform(value: string): value is Platform {
	return (PLATFORMS as readonly string[]).includes(value);
}

export function hostPlatform(
	platform: string = process.platform,
	arch: string = process.arch,
): Platform {
	const os =
		platform === "darwin" ? "darwin" : platform === "linux" ? "linux" : null;
	const cpu = arch === "arm64" ? "arm64" : arch === "x64" ? "x64" : null;
	if (os === null || cpu === null) {
		throw new Error(
			`Cannot build on ${platform}-${arch}. NOTAM ships ${PLATFORMS.join(", ")}.`,
		);
	}
	return `${os}-${cpu}`;
}

/**
 * Renders the compile entrypoint.
 *
 * Every asset arrives as a static `with { type: "file" }` import because that
 * is the only thing `bun build --compile` embeds, and the imported value is a
 * path `Bun.file` can read — the real one when running from source, a
 * `/$bunfs/root/...` one inside the binary. The set of files is Vite's
 * content-hashed output, so no hand-written module could name them; this is
 * why the entrypoint is generated.
 */
export function renderEntryModule(
	webPaths: string[],
	distImportBase = "../web/dist",
): string {
	if (webPaths.length === 0) {
		throw new Error(
			"There are no web assets to embed. Run `bun run build:web` first.",
		);
	}
	const imports: string[] = [];
	const entries: string[] = [];
	// Sorted, so the same web/dist always renders the same bytes.
	[...webPaths].sort().forEach((path, index) => {
		if (!path.startsWith("/")) {
			throw new Error(`Asset paths must be web-rooted, got "${path}".`);
		}
		imports.push(
			`import asset${index} from ${JSON.stringify(
				`${distImportBase}${path}`,
			)} with { type: "file" };`,
		);
		entries.push(`\t{ path: ${JSON.stringify(path)}, file: asset${index} },`);
	});

	return `// Generated by scripts/build-binary.ts. Do not edit, do not commit.
import { main } from "../src/cli/index.ts";
import { registerEmbeddedAssets } from "../src/server/embedded.ts";
${imports.join("\n")}

registerEmbeddedAssets([
${entries.join("\n")}
]);

process.exit(await main(Bun.argv.slice(2)));
`;
}
