/**
 * The generator for `build/entry.ts`, the entrypoint `bun build --compile` is
 * pointed at.
 *
 * Kept apart from `build-binary.ts` so the interesting half — string in, string
 * out — is testable without compiling a 60 MB executable.
 */

/**
 * Renders the compile entrypoint.
 *
 * Every asset arrives as a static `with { type: "file" }` import because that
 * is the only thing `bun build --compile` embeds, and the imported value is a
 * path `Bun.file` can read — the real one when running from source, a
 * `/$bunfs/root/...` one inside the binary. The set of files is Vite's
 * content-hashed output, so no hand-written module could name them; this is
 * why the entrypoint is generated.
 */
export function renderEntryModule(
	webPaths: string[],
	distImportBase = "../web/dist",
): string {
	if (webPaths.length === 0) {
		throw new Error(
			"There are no web assets to embed. Run `bun run build:web` first.",
		);
	}
	const imports: string[] = [];
	const entries: string[] = [];
	// Sorted, so the same web/dist always renders the same bytes.
	[...webPaths].sort().forEach((path, index) => {
		if (!path.startsWith("/")) {
			throw new Error(`Asset paths must be web-rooted, got "${path}".`);
		}
		imports.push(
			`import asset${index} from ${JSON.stringify(
				`${distImportBase}${path}`,
			)} with { type: "file" };`,
		);
		entries.push(`\t{ path: ${JSON.stringify(path)}, file: asset${index} },`);
	});

	return `// Generated by scripts/build-binary.ts. Do not edit, do not commit.
import { main } from "../src/cli/index.ts";
import { registerEmbeddedAssets } from "../src/server/embedded.ts";
${imports.join("\n")}

registerEmbeddedAssets([
${entries.join("\n")}
]);

process.exit(await main(Bun.argv.slice(2)));
`;
}
