import { describe, expect, test } from "bun:test";
import {
	hostPlatform,
	isPlatform,
	PLATFORMS,
	renderEntryModule,
} from "../../scripts/entry-module.ts";

describe("the platform table", () => {
	test("is exactly the four shipped targets", () => {
		expect([...PLATFORMS]).toEqual([
			"darwin-arm64",
			"darwin-x64",
			"linux-x64",
			"linux-arm64",
		]);
	});

	test("recognises its own members and nothing else", () => {
		expect(isPlatform("linux-arm64")).toBe(true);
		expect(isPlatform("win32-x64")).toBe(false);
	});

	test("maps a host's platform and arch onto one of them", () => {
		expect(hostPlatform("darwin", "arm64")).toBe("darwin-arm64");
		expect(hostPlatform("linux", "x64")).toBe("linux-x64");
	});

	test("refuses a host it cannot build for", () => {
		expect(() => hostPlatform("win32", "x64")).toThrow("win32-x64");
	});
});

describe("renderEntryModule", () => {
	test("emits one file import per asset, in sorted order", () => {
		expect(
			renderEntryModule(["/index.html", "/assets/app-abc123.js"]),
		).toBe(`// Generated by scripts/build-binary.ts. Do not edit, do not commit.
import { main } from "../src/cli/index.ts";
import { registerEmbeddedAssets } from "../src/server/embedded.ts";
import asset0 from "../web/dist/assets/app-abc123.js" with { type: "file" };
import asset1 from "../web/dist/index.html" with { type: "file" };

registerEmbeddedAssets([
	{ path: "/assets/app-abc123.js", file: asset0 },
	{ path: "/index.html", file: asset1 },
]);

process.exit(await main(Bun.argv.slice(2)));
`);
	});

	test("honours a different dist location", () => {
		expect(renderEntryModule(["/index.html"], "../elsewhere/dist")).toContain(
			'import asset0 from "../elsewhere/dist/index.html" with { type: "file" };',
		);
	});

	test("refuses to render a binary with no web UI in it", () => {
		expect(() => renderEntryModule([])).toThrow("bun run build:web");
	});

	test("refuses a path that is not web-rooted", () => {
		expect(() => renderEntryModule(["index.html"])).toThrow("web-rooted");
	});
});
